### ISSUE TITLE
nw11 - developer tools no longer works

### ISSUE THREAD

**Issue by cchersin** [rogerwang/node-webkit#2603]
Node webkit 0.11.0 for windows 32 bit.  Developer tools shows an empty page

**Comment by cchersin** [comment]
Any plan to to fix it? Workarounds?
I need some features/fix from 0.11 but i can't upgrade due to this issue.

**Comment by ghostoy** [comment]
@cchersin Github doesn't receive attachment. Could you share your test case through cloud services, like Dropbox?
