### ISSUE TITLE
`copy` doesn't work in devtools

### ISSUE THREAD

**Issue by ghostoy** [rogerwang/node-webkit#2660]
## Steps to reproduce
* Open devtools
* Type `copy('abcd')`

## Expected Result
`'abcd'` is copied to clipboard without any error

## Actual Result
Throw an error "Clipboard is not enabled in hosted mode. Please inspect using chrome://inspect"

**Comment by eugirdor** [comment]
This seems to be occurring again in 0.12 on Mac OS X
