### ISSUE TITLE
Alert and confirm js functions are not showing dialogs on 0.11.1

### ISSUE THREAD

**Issue by uggrock** [rogerwang/node-webkit#2683]
alert() returns undefined and confirm() returns alway false in console

**Comment by bryceosterhaus** [comment]
on version 0.11.5, issue is still reproducible on 64bit linux. I would also very much appreciate a fix to this! Thank you

**Comment by hugecannon** [comment]
Alert/Confirm/Prompt not working for me on Ubuntu 14.04.1 + NW v0.11.3

**Comment by rogerwang** [comment]
This is fixed in the 'nw12' branch, will be released with v0.12.

Now you can try it from the live build: http://dl.node-webkit.org/live-build/01-07-2015/e46d09d-02026f1-b477a2d-2e978ac-8c5a736-fd87c8d/
