### ISSUE TITLE
listeners iframe.addEventListener('load') not trigger for NW0.11

### ISSUE THREAD

**Issue by ghostoy** [rogerwang/node-webkit#2867]
Code to reproduce:

```javascript
  function createIframe() {
    var html = '<iframe style="width:100%;height:100%;"></iframe>';
    var $out = document.getElementById('out').innerHTML = html;
    var $iframe = document.getElementsByTagName('iframe')[0];

    $iframe.onload = function(){
      console.log('onload');
    };

    $iframe.addEventListener('load', function() {
      console.log('addEventListener(load)');
    }, false);

    $iframe.src = 'http://en.wikipedia.org/wiki/Main_Page';
  }
```

On 0.10.5, two listeners are triggered. On 0.11.2, 0.11.3, 0.11.4, only "onload" listener is triggered.

**Comment by uggrock** [comment]
I can confirm this issue, on Ubuntu 64bit with 0.11.4

**Comment by ghostoy** [comment]
Seems like this issue only happens only when devtools is open. If devtools is not open, both events are fired.

**Comment by cperkinsintel** [comment]
I am seeing this issue whether I open devtools or not. 

 I may need to look into using the node-webkit specific events (https://github.com/rogerwang/node-webkit/wiki/Window#document-start ) instead.

**Comment by busykai** [comment]
FWIW it sounds like if the src is set from the beginning, `load` event actually comes in.

**Comment by rogerwang** [comment]
http://dl.node-webkit.org/live-build/01-09-2015/16340c2-d8ecacd-9a15a52-f2f89e2-d9a9d39-cdd879e/

**Comment by ghostoy** [comment]
Confirmed. Thanks roger.
