### ISSUE TITLE
Static http-server?

### ISSUE THREAD

**Issue by kpourdeilami** [rogerwang/node-webkit#2901]
I know this has been asked and been rejected before but seriously filesystem has many limitations. The most important one being that I can't use any Google API's or google/facebook login because they require a callback url or whitelisted javascript origins. Any tips on how to start a local http-server on launch (i.e http://localhost:8080) and navigate to it?

**Comment by edi9999** [comment]
You could create an index.html that would:

 * Run `server.js` powered by express in the background using something like `require('child_process').spawn`

 * After a few seconds (or after a response to stdout), do `window.location="http://localhost:8080";`

I don't think that node-webkit should ship with a static server, it's quite easy to implement yourself

**Comment by kpourdeilami** [comment]
@edi9999 Thanks for the response. I tried doing it this way

```
<!DOCTYPE html>
<html>
<head>
    <script>
        var express = require('express');
        var http = require('http');
        var server = express();
        http.get('http://localhost:8080', function(res) {
            console.log('server is running, redirecting to localhost');
            if (window.location.href.indexOf('localhost') < 0) {
                window.location = 'http://localhost:8080';
            }
        }).on('error', function(e) {
            server.configure(function(){
                server.use('/build', express.static(__dirname + '/build'));
                server.use('/packages', express.static(__dirname + '/packages'));
                server.use('/partials', express.static(__dirname + '/partials'));
                server.use(express.static(__dirname));
            });
            server.listen(8080);
        });
    </script>
</head>
<body>
<h1>STARTING LOCAL SERVER</h1>
</body>
</html>
```
but didn't work. Any tips on how to get this into a child process?

**Comment by kpourdeilami** [comment]
Never mind got it to work with this:

```
<!DOCTYPE html>
<html>
<head>
    <script>
        var connect = require('connect');
        var serveStatic = require('serve-static');
        var path = require('path');
        connect().use(serveStatic('./')).listen(3000);
        if (window.location.href.indexOf('localhost') < 0) {
            window.location = 'http://localhost:3000';
        }
    </script>
</head>
<body>
<h1>STARTING LOCAL SERVER</h1>
</body>
</html>
```

In case people run into the same issue

**Comment by edi9999** [comment]
This issue should be closed now

**Comment by forhappy** [comment]
Hi, I tried this method, it works OK when I connect an US VPN or start my Charles, but when I close the VPN or did not start Charles, this can not work, express has the same problem too: https://github.com/jaeh/node-webkit-express,

Here is my descriptions: https://github.com/nwjs/nw.js/issues/3664

Would someone help find out why ?
