### ISSUE TITLE
'Pass through' mouse events?

### ISSUE THREAD

**Issue by MarcFowler** [rogerwang/node-webkit#2902]
Now that transparency is possible, it would be really awesome if it were possible to use something like CSS's `pointer-events` property to allow passing through mouse events to underlying windows.

For example, think of a drawing tool. You'd make a 100% wide and high, transparent, frameless 'window' and add your content to it. But the user would be able to use their computer as normal whilst this was active.

(I've confirmed that `pointer-events: none;` doesn't work on the html and/or body elements - it doesn't pass the clicks etc through)

This would be amazing to implement - is it possible?

**Comment by adam-lynch** [comment]
Did you see https://github.com/rogerwang/node-webkit/wiki/Transparency#click-through-transparency?

**Comment by MarcFowler** [comment]
Haha.. no, no I didn't. That's awesome.

I'm checking it out now. I'll reopen if I have any issues but so far it seems to be working great. Thanks!!

**Comment by kensully** [comment]
Click-through event is not supported in Linux currently, am I wrong?

**Comment by edi9999** [comment]
Yes not for linux right now

**Comment by jtg-gg** [comment]
@MarcFowler have you tried the latest 0.11.5? I've added support for pass through mouse events
see more info on how to activate it here https://github.com/rogerwang/node-webkit/wiki/Transparency

**Comment by jtg-gg** [comment]
@kensully @edi9999 I've tried to do it on Ubuntu, but most of sample code I found, does not work, if anyone can give me some simple sample code, I would love to support click through on linux

**Comment by kensully** [comment]
@jtg-gg 
Do you mean you need a clickthrough example in Linux? Once I also tried to find a way to implement clickthrough in Linux. Unfourtunately there are not many examples of it.  What I found was ECERE's XShape extension. It works. http://www.ecere.com/blog/category/releases/page/2/
I hope it helps.

**Comment by jtg-gg** [comment]
@kensully thx, but I can't run the binary in ubuntu "error while loading shared libraries: libX11.so.6: cannot open shared"

and I would prefer a simple c code using x11, rather than binary / app with library to compile

**Comment by kensully** [comment]
@jtg-gg  ECERE is open source in github https://github.com/ecere/ecere-sdk
Anyway I found a more simple click through example in Linux. It's `xeyes` Open terminal and type `xeyes` it's preinstalled. Here is the source  code ftp://ftp.x.org/pub/unsupported/programs/xeyes/
I could compile it like `gcc -o  xeyes   xeyes.c Eyes.c transform.c -lX11 -lXt  -lXext  -lXmu -lm`

**Comment by baongoc124** [comment]
Hey guys, I'm not a nwjs user but I googled and found this issue. Anw, I think I have real example of a click-through window in Linux. It's in the notify-osd program of Ubuntu. You can see pretty clear how they get it done here https://github.com/dkasak/notify-osd-customizable/blob/master/src/bubble.c#L1608 . And another requirement is that the window's type must be popup.

**Comment by kensully** [comment]
in this link you ll find the simplest example of pass-through but it uses an outdated linux library.   It works very well though http://ubuntuforums.org/attachment.php?attachmentid=43756&d=1190115279
