### ISSUE TITLE
Support for styling ::webkit-scrollbar pseudo elements

### ISSUE THREAD

**Issue by 4ver** [rogerwang/node-webkit#2910]
They doesn't work in v0.11.x

Cheers!

**Comment by studiochris** [comment]
All of the following are working for me in 0.11.5 on Windows 8.1:

- `::-webkit-scrollbar`
- `::-webkit-scrollbar-button:start:decrement`
- `::-webkit-scrollbar-button:end:increment`
- `::-webkit-scrollbar-track`
- `::-webkit-scrollbar-thumb`
- `::-webkit-scrollbar-thumb:horizontal`
- `::-webkit-scrollbar-thumb:vertical`

Do you have an example that others could try?

**Comment by adam-lynch** [comment]
Hmm I tried what @studiochris said and it worked for two of the three scrollbars I could see. Not sure why it didn't do all of them, I've no special JS/CSS going on there.

**Comment by 4ver** [comment]
@studiochris I was trying to use them on a mac :smile: oops
